// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0JeJpfFSCP7x3THvKdO8GHiucufs0IQ',
    appId: '1:970362926725:android:b733405f0b816037b6dbec',
    messagingSenderId: '970362926725',
    projectId: 'radioprogreso-a03a6',
    databaseURL: 'https://radioprogreso-a03a6.firebaseio.com',
    storageBucket: 'radioprogreso-a03a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGTcIpCdd0uJC__aKkvWu5oQWFZKh9fI',
    appId: '1:970362926725:ios:ed23b19854bf9b08b6dbec',
    messagingSenderId: '970362926725',
    projectId: 'radioprogreso-a03a6',
    databaseURL: 'https://radioprogreso-a03a6.firebaseio.com',
    storageBucket: 'radioprogreso-a03a6.appspot.com',
    androidClientId: '970362926725-1a6o1oquvd3o8npkjb72mopmslitgiev.apps.googleusercontent.com',
    iosClientId: '970362926725-0bu3ji3rms00pkqc6f9omur4n22381c9.apps.googleusercontent.com',
    iosBundleId: 'net.radioprogresohn.appoficial',
  );
}
